theme: minima
title: Maduranga's Thoughts
description: Notes from my journey becoming an AI engineer.
author: Maduranga Senadheera

minima:
  show_author: false

exclude:
  - versions/

header_pages:
  - blog.md
