theme: minima
title: Maduranga's Thoughts
description: On a journey toward AI engineering.
author: Maduranga Senadheera

minima:
  show_author: false

exclude:
  - index.html
  - assets/
  - certificates/
  - versions/

header_pages:
  - blog.md
