theme: minima
title: Maduranga's Thoughts
description: Just a full-stack developer, accidentally walking into AI engineering ğŸš¶â€â™‚ï¸ğŸ¤–
author: Maduranga Senadheera

minima:
  show_author: false

exclude:
  - index.html
  - assets/
  - certificates/
  - versions/

header_pages:
  - blog.md
