theme: minima
title: Maduranga Thoughts
description: Senior Full-Stack Developer | React • Next.js • Node.js
author:
  name: Maduranga Senadheera

minima:
  show_author: false

exclude:
  - index.html
  - assets/
  - certificates/
  - versions/

header_pages:
  - blog.md
