theme: minima
title: Maduranga's Thoughts
description: Senior Full-Stack Developer | React • Next.js • Node.js
 
minima:
  show_author: false

exclude:
  - index.html
  - assets/
  - certificates/
  - versions/

header_pages:
  - blog.md
